"""
Candidate Action Model — CONFIRMED, Phase 16 §6 (exhaustive list).
No Action Type may be added beyond this set without a documented
Phase 16 amendment.
"""

CONTINUE = "CONTINUE"
PRACTICE_EASIER = "PRACTICE_EASIER"
PRACTICE_HARDER = "PRACTICE_HARDER"
REVIEW_CONCEPT = "REVIEW_CONCEPT"
REVIEW_PREREQUISITE = "REVIEW_PREREQUISITE"
TRIGGER_EXPLANATION = "TRIGGER_EXPLANATION"
UNLOCK_ASSESSMENT = "UNLOCK_ASSESSMENT"
UNLOCK_PROJECT = "UNLOCK_PROJECT"
STAY = "STAY"

ALL_ACTIONS = {
    CONTINUE, PRACTICE_EASIER, PRACTICE_HARDER, REVIEW_CONCEPT, REVIEW_PREREQUISITE,
    TRIGGER_EXPLANATION, UNLOCK_ASSESSMENT, UNLOCK_PROJECT, STAY,
}