# Generated by Django 5.0.6 on 2026-09-19 11:10

import apps.identity.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.identity.managers.UserManager()),
            ],
        ),
    ]
